// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CyberCity.Doman.Models;

public partial class Answer
{
    public string Uid { get; set; }

    public string SubtopicUid { get; set; }

    public string ExpectedOutput { get; set; }

    public string CheckType { get; set; }

    public bool? CaseSensitive { get; set; }

    public bool? TrimWhitespace { get; set; }

    public string Explanation { get; set; }

    public string Hints { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Subtopic SubtopicU { get; set; }
}