// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CyberCity.Doman.Models;

public partial class ApprovalLog
{
    public string Uid { get; set; }

    public string OrderUid { get; set; }

    public string ApprovedBy { get; set; }

    public string Status { get; set; }

    public string Note { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual User ApprovedByNavigation { get; set; }

    public virtual Order OrderU { get; set; }
}