// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CyberCity.Doman.Models;

public partial class Assignment
{
    public Guid Uid { get; set; }

    public Guid CourseUid { get; set; }

    public Guid? LessonUid { get; set; }

    public Guid? SubtopicUid { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public DateTime? DueAt { get; set; }

    public Guid CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string AssignmentType { get; set; }

    public virtual Course CourseU { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual Lesson LessonU { get; set; }

    public virtual ICollection<Submission> Submissions { get; set; } = new List<Submission>();

    public virtual Subtopic SubtopicU { get; set; }
}