// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CyberCity.Doman.Models;

public partial class Certificate
{
    public Guid Uid { get; set; }

    public Guid UserUid { get; set; }

    public Guid CourseUid { get; set; }

    public string CertificateType { get; set; }

    public decimal? Score { get; set; }

    public decimal? CompletionPercentage { get; set; }

    public string FileUrl { get; set; }

    public DateTime? IssuedAt { get; set; }

    public virtual Course CourseU { get; set; }

    public virtual User UserU { get; set; }
}