// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CyberCity.Doman.Models;

public partial class ConversationMember
{
    public string Uid { get; set; }

    public string ConversationUid { get; set; }

    public string UserUid { get; set; }

    public DateTime? JoinedAt { get; set; }

    public virtual Conversation ConversationU { get; set; }

    public virtual User UserU { get; set; }
}