// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CyberCity.Doman.Models;

public partial class Conversation
{
    public Guid Uid { get; set; }

    public Guid? OrgUid { get; set; }

    public string Title { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<ConversationMember> ConversationMembers { get; set; } = new List<ConversationMember>();

    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();

    public virtual Organization Or { get; set; }
}