// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CyberCity.Doman.Models;

public partial class CourseEnrollment
{
    public Guid Uid { get; set; }

    public Guid UserUid { get; set; }

    public Guid CourseUid { get; set; }

    public DateTime? EnrolledAt { get; set; }

    public virtual Course CourseU { get; set; }

    public virtual User UserU { get; set; }
}