// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CyberCity.Doman.Models;

public partial class CourseEnrollment
{
    public string Uid { get; set; }

    public string UserUid { get; set; }

    public string CourseUid { get; set; }

    public DateTime? EnrolledAt { get; set; }

    public virtual Course CourseU { get; set; }

    public virtual User UserU { get; set; }
}