// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CyberCity.Doman.Models;

public partial class Lab
{
    public string Uid { get; set; }

    public string ModuleUid { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string LabType { get; set; }

    public bool? IsRequired { get; set; }

    public int? OrderIndex { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<LabComponent> LabComponents { get; set; } = new List<LabComponent>();

    public virtual Module ModuleU { get; set; }
}