// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CyberCity.Doman.Models;

public partial class LabComponent
{
    public string Uid { get; set; }

    public string LabUid { get; set; }

    public string ComponentName { get; set; }

    public string ComponentType { get; set; }

    public string OsInfo { get; set; }

    public string AccessDetails { get; set; }

    public bool? IsVulnerable { get; set; }

    public int? OrderIndex { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Lab LabU { get; set; }
}