// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CyberCity.Doman.Models;

public partial class Lesson
{
    public Guid Uid { get; set; }

    public Guid ModuleUid { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public string LessonType { get; set; }

    public int? OrderIndex { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Module ModuleU { get; set; }

    public virtual ICollection<Topic> Topics { get; set; } = new List<Topic>();
}