// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CyberCity.Doman.Models;

public partial class LessonProgress
{
    public Guid Uid { get; set; }

    public Guid StudentUid { get; set; }

    public Guid LessonUid { get; set; }

    public string Status { get; set; }

    public DateTime? CompletedAt { get; set; }

    public virtual Lesson LessonU { get; set; }

    public virtual User StudentU { get; set; }
}