// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CyberCity.Doman.Models;

public partial class Message
{
    public string Uid { get; set; }

    public string ConversationUid { get; set; }

    public string SenderUid { get; set; }

    public string Message1 { get; set; }

    public DateTime? SentAt { get; set; }

    public virtual Conversation ConversationU { get; set; }

    public virtual User SenderU { get; set; }
}