// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CyberCity.Doman.Models;

public partial class Module
{
    public string Uid { get; set; }

    public string CourseUid { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public int? OrderIndex { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Course CourseU { get; set; }

    public virtual ICollection<Lab> Labs { get; set; } = new List<Lab>();

    public virtual ICollection<Lesson> Lessons { get; set; } = new List<Lesson>();
}