// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CyberCity.Doman.Models;

public partial class Notification
{
    public Guid Uid { get; set; }

    public Guid ReceiverUid { get; set; }

    public Guid? SenderUid { get; set; }

    public string Message { get; set; }

    public bool? IsRead { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual User ReceiverU { get; set; }

    public virtual User SenderU { get; set; }
}