// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CyberCity.Doman.Models;

public partial class Order
{
    public string Uid { get; set; }

    public string UserUid { get; set; }

    public string OrgUid { get; set; }

    public string PlanUid { get; set; }

    public decimal Amount { get; set; }

    public string PaymentStatus { get; set; }

    public string ApprovalStatus { get; set; }

    public DateTime? StartAt { get; set; }

    public DateTime? EndAt { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<ApprovalLog> ApprovalLogs { get; set; } = new List<ApprovalLog>();

    public virtual Organization Or { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual PricingPlan PlanU { get; set; }

    public virtual User UserU { get; set; }
}