// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CyberCity.Doman.Models;

public partial class Organization
{
    public string Uid { get; set; }

    public string OrgName { get; set; }

    public string OrgType { get; set; }

    public string ContactEmail { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<Conversation> Conversations { get; set; } = new List<Conversation>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<OrgMember> OrgMembers { get; set; } = new List<OrgMember>();
}