// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CyberCity.Doman.Models;

public partial class OrgMember
{
    public string Uid { get; set; }

    public string OrgUid { get; set; }

    public string UserUid { get; set; }

    public string MemberRole { get; set; }

    public DateTime? JoinedAt { get; set; }

    public virtual Organization Or { get; set; }

    public virtual User UserU { get; set; }
}