// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CyberCity.Doman.Models;

public partial class Payment
{
    public string Uid { get; set; }

    public string OrderUid { get; set; }

    public string PaymentMethod { get; set; }

    public string TransactionCode { get; set; }

    public decimal Amount { get; set; }

    public string Currency { get; set; }

    public string Status { get; set; }

    public DateTime? PaidAt { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Order OrderU { get; set; }
}