// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CyberCity.Doman.Models;

public partial class PricingPlan
{
    public Guid Uid { get; set; }

    public string PlanName { get; set; }

    public decimal Price { get; set; }

    public int DurationDays { get; set; }

    public string Features { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}