// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CyberCity.Doman.Models;

public partial class Quiz
{
    public string Uid { get; set; }

    public string LessonUid { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public int? TotalQuestions { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Lesson LessonU { get; set; }

    public virtual ICollection<QuizQuestion> QuizQuestions { get; set; } = new List<QuizQuestion>();

    public virtual ICollection<QuizSubmission> QuizSubmissions { get; set; } = new List<QuizSubmission>();
}