// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CyberCity.Doman.Models;

public partial class QuizSubmission
{
    public string Uid { get; set; }

    public string QuizUid { get; set; }

    public string StudentUid { get; set; }

    public decimal? Score { get; set; }

    public DateTime? SubmittedAt { get; set; }

    public virtual ICollection<QuizSubmissionAnswer> QuizSubmissionAnswers { get; set; } = new List<QuizSubmissionAnswer>();

    public virtual Quiz QuizU { get; set; }

    public virtual User StudentU { get; set; }
}