// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CyberCity.Doman.Models;

public partial class QuizSubmissionAnswer
{
    public string Uid { get; set; }

    public string SubmissionUid { get; set; }

    public string QuestionUid { get; set; }

    public string SelectedAnswerUid { get; set; }

    public bool? IsCorrect { get; set; }

    public virtual QuizQuestion QuestionU { get; set; }

    public virtual QuizAnswer SelectedAnswerU { get; set; }

    public virtual QuizSubmission SubmissionU { get; set; }
}