// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CyberCity.Doman.Models;

public partial class Submission
{
    public Guid Uid { get; set; }

    public Guid AssignmentUid { get; set; }

    public Guid StudentUid { get; set; }

    public string Status { get; set; }

    public string AnswerText { get; set; }

    public DateTime? SubmittedAt { get; set; }

    public decimal? Grade { get; set; }

    public string Feedback { get; set; }

    public virtual Assignment AssignmentU { get; set; }

    public virtual User StudentU { get; set; }
}