// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CyberCity.Doman.Models;

public partial class Subtopic
{
    public Guid Uid { get; set; }

    public Guid TopicUid { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public int? OrderIndex { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<SubtopicProgress> SubtopicProgresses { get; set; } = new List<SubtopicProgress>();

    public virtual Topic TopicU { get; set; }
}