// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CyberCity.Doman.Models;

public partial class SubtopicProgress
{
    public string Uid { get; set; }

    public string StudentUid { get; set; }

    public string SubtopicUid { get; set; }

    public bool? IsCompleted { get; set; }

    public DateTime? CompletedAt { get; set; }

    public string UserOutput { get; set; }

    public bool? IsCorrect { get; set; }

    public int? AttemptCount { get; set; }

    public DateTime? LastAttemptedAt { get; set; }

    public virtual User StudentU { get; set; }

    public virtual Subtopic SubtopicU { get; set; }
}