// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CyberCity.Doman.Models;

public partial class TeacherStudent
{
    public Guid Uid { get; set; }

    public Guid TeacherUid { get; set; }

    public Guid StudentUid { get; set; }

    public Guid CourseUid { get; set; }

    public virtual Course CourseU { get; set; }

    public virtual User StudentU { get; set; }

    public virtual User TeacherU { get; set; }
}