// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CyberCity.Doman.Models;

public partial class TeacherStudent
{
    public string Uid { get; set; }

    public string TeacherUid { get; set; }

    public string StudentUid { get; set; }

    public string CourseUid { get; set; }

    public virtual Course CourseU { get; set; }

    public virtual User StudentU { get; set; }

    public virtual User TeacherU { get; set; }
}