// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CyberCity.Doman.Models;

public partial class Topic
{
    public Guid Uid { get; set; }

    public Guid LessonUid { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }


    public int? OrderIndex { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Lesson LessonU { get; set; }

    public virtual ICollection<Subtopic> Subtopics { get; set; } = new List<Subtopic>();
}