// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CyberCity.Doman.Models;

public partial class User
{
    public Guid Uid { get; set; }

    public string Email { get; set; }

    public string Username { get; set; }

    public string PasswordHash { get; set; }

    public string FullName { get; set; }

    public string Role { get; set; }

    public DateTime? CreatedAt { get; set; }
    public string Image { get; set; }
    public string Status { get; set; }

    public virtual ICollection<ApprovalLog> ApprovalLogs { get; set; } = new List<ApprovalLog>();

    public virtual ICollection<Assignment> Assignments { get; set; } = new List<Assignment>();

    public virtual ICollection<Certificate> Certificates { get; set; } = new List<Certificate>();

    public virtual ICollection<ConversationMember> ConversationMembers { get; set; } = new List<ConversationMember>();

    public virtual ICollection<CourseEnrollment> CourseEnrollments { get; set; } = new List<CourseEnrollment>();

    public virtual ICollection<CourseGrade> CourseGradeGradedByNavigations { get; set; } = new List<CourseGrade>();

    public virtual ICollection<CourseGrade> CourseGradeStudentUs { get; set; } = new List<CourseGrade>();

    public virtual ICollection<CourseProgress> CourseProgresses { get; set; } = new List<CourseProgress>();

    public virtual ICollection<Course> Courses { get; set; } = new List<Course>();

    public virtual ICollection<LessonProgress> LessonProgresses { get; set; } = new List<LessonProgress>();

    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();

    public virtual ICollection<Notification> NotificationReceiverUs { get; set; } = new List<Notification>();

    public virtual ICollection<Notification> NotificationSenderUs { get; set; } = new List<Notification>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<OrgMember> OrgMembers { get; set; } = new List<OrgMember>();

    public virtual ICollection<Submission> Submissions { get; set; } = new List<Submission>();

    public virtual ICollection<TeacherStudent> TeacherStudentStudentUs { get; set; } = new List<TeacherStudent>();

    public virtual ICollection<TeacherStudent> TeacherStudentTeacherUs { get; set; } = new List<TeacherStudent>();
}