// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CyberCity.Doman.Models;

public partial class VwCourseOutline
{
    public string CourseUid { get; set; }

    public string CourseTitle { get; set; }

    public string ModuleUid { get; set; }

    public string ModuleTitle { get; set; }

    public int? ModuleOrder { get; set; }

    public string LessonUid { get; set; }

    public string LessonTitle { get; set; }

    public string LessonType { get; set; }

    public int? LessonOrder { get; set; }

    public string TopicUid { get; set; }

    public string TopicTitle { get; set; }

    public int? TopicPage { get; set; }

    public int? TopicOrder { get; set; }

    public string SubtopicUid { get; set; }

    public string SubtopicTitle { get; set; }

    public int? SubtopicOrder { get; set; }
}